// flow-typed signature: b8354baf46e252f0a241c96a45fc34cd
// flow-typed version: <<STUB>>/react-scripts_v^2.0.0-next.3e165448/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-scripts" {
  let __exports: any;
  export = __exports;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-scripts/bin/react-scripts" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/env" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/jest/babelTransform" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/jest/cssTransform" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/jest/fileTransform" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/jest/graphqlTransform" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/paths" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/polyfills" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/webpack.config.dev" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/webpack.config.prod" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/config/webpackDevServer.config" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/scripts/build" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/scripts/eject" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/scripts/init" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/scripts/start" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/scripts/test" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/scripts/utils/createJestConfig" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/scripts/utils/verifyPackageTree" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/template/src/App" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/template/src/App.test" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/template/src/index" {
  let __exports: any;
  export = __exports;
}

declare module "react-scripts/template/src/serviceWorker" {
  let __exports: any;
  export = __exports;
}

// Filename aliases
declare module "react-scripts/bin/react-scripts.js" {
  let __exports: import("react-scripts/bin/react-scripts");
  export = __exports;
}

declare module "react-scripts/config/env.js" {
  let __exports: import("react-scripts/config/env");
  export = __exports;
}

declare module "react-scripts/config/jest/babelTransform.js" {
  let __exports: import("react-scripts/config/jest/babelTransform");
  export = __exports;
}

declare module "react-scripts/config/jest/cssTransform.js" {
  let __exports: import("react-scripts/config/jest/cssTransform");
  export = __exports;
}

declare module "react-scripts/config/jest/fileTransform.js" {
  let __exports: import("react-scripts/config/jest/fileTransform");
  export = __exports;
}

declare module "react-scripts/config/jest/graphqlTransform.js" {
  let __exports: import("react-scripts/config/jest/graphqlTransform");
  export = __exports;
}

declare module "react-scripts/config/paths.js" {
  let __exports: import("react-scripts/config/paths");
  export = __exports;
}

declare module "react-scripts/config/polyfills.js" {
  let __exports: import("react-scripts/config/polyfills");
  export = __exports;
}

declare module "react-scripts/config/webpack.config.dev.js" {
  let __exports: import("react-scripts/config/webpack.config.dev");
  export = __exports;
}

declare module "react-scripts/config/webpack.config.prod.js" {
  let __exports: import("react-scripts/config/webpack.config.prod");
  export = __exports;
}

declare module "react-scripts/config/webpackDevServer.config.js" {
  let __exports: import("react-scripts/config/webpackDevServer.config");
  export = __exports;
}

declare module "react-scripts/scripts/build.js" {
  let __exports: import("react-scripts/scripts/build");
  export = __exports;
}

declare module "react-scripts/scripts/eject.js" {
  let __exports: import("react-scripts/scripts/eject");
  export = __exports;
}

declare module "react-scripts/scripts/init.js" {
  let __exports: import("react-scripts/scripts/init");
  export = __exports;
}

declare module "react-scripts/scripts/start.js" {
  let __exports: import("react-scripts/scripts/start");
  export = __exports;
}

declare module "react-scripts/scripts/test.js" {
  let __exports: import("react-scripts/scripts/test");
  export = __exports;
}

declare module "react-scripts/scripts/utils/createJestConfig.js" {
  let __exports: import("react-scripts/scripts/utils/createJestConfig");
  export = __exports;
}

declare module "react-scripts/scripts/utils/verifyPackageTree.js" {
  let __exports: import("react-scripts/scripts/utils/verifyPackageTree");
  export = __exports;
}

declare module "react-scripts/template/src/App.js" {
  let __exports: import("react-scripts/template/src/App");
  export = __exports;
}

declare module "react-scripts/template/src/App.test.js" {
  let __exports: import("react-scripts/template/src/App.test");
  export = __exports;
}

declare module "react-scripts/template/src/index.js" {
  let __exports: import("react-scripts/template/src/index");
  export = __exports;
}

declare module "react-scripts/template/src/serviceWorker.js" {
  let __exports: import("react-scripts/template/src/serviceWorker");
  export = __exports;
}
