// flow-typed signature: 50e7e3470cf67e07285dae40391aaa09
// flow-typed version: <<STUB>>/react-promise_v^2.0.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-promise" {
  let __exports: any;
  export = __exports;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-promise/dist/react-promise.cjs" {
  let __exports: any;
  export = __exports;
}

declare module "react-promise/dist/react-promise.es" {
  let __exports: any;
  export = __exports;
}

declare module "react-promise/src/react-promise" {
  let __exports: any;
  export = __exports;
}

declare module "react-promise/src/react-promise.spec" {
  let __exports: any;
  export = __exports;
}

// Filename aliases
declare module "react-promise/dist/react-promise.cjs.js" {
  let __exports: import("react-promise/dist/react-promise.cjs");
  export = __exports;
}

declare module "react-promise/dist/react-promise.es.js" {
  let __exports: import("react-promise/dist/react-promise.es");
  export = __exports;
}

declare module "react-promise/src/react-promise.js" {
  let __exports: import("react-promise/src/react-promise");
  export = __exports;
}

declare module "react-promise/src/react-promise.spec.js" {
  let __exports: import("react-promise/src/react-promise.spec");
  export = __exports;
}
