// flow-typed signature: 50e7e3470cf67e07285dae40391aaa09
// flow-typed version: <<STUB>>/react-promise_v^2.0.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-promise/dist/react-promise.cjs' {
  declare module.exports: any;
}

declare module 'react-promise/dist/react-promise.es' {
  declare module.exports: any;
}

declare module 'react-promise/src/react-promise' {
  declare module.exports: any;
}

declare module 'react-promise/src/react-promise.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-promise/dist/react-promise.cjs.js' {
  declare module.exports: $Exports<'react-promise/dist/react-promise.cjs'>;
}
declare module 'react-promise/dist/react-promise.es.js' {
  declare module.exports: $Exports<'react-promise/dist/react-promise.es'>;
}
declare module 'react-promise/src/react-promise.js' {
  declare module.exports: $Exports<'react-promise/src/react-promise'>;
}
declare module 'react-promise/src/react-promise.spec.js' {
  declare module.exports: $Exports<'react-promise/src/react-promise.spec'>;
}
