// flow-typed signature: 99b041f2ee30f052d16e19bbae9fa190
// flow-typed version: <<STUB>>/source-map-explorer_v^1.5.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-explorer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "source-map-explorer" {
  let __exports: any;
  export = __exports;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "source-map-explorer/test" {
  let __exports: any;
  export = __exports;
}

declare module "source-map-explorer/testdata/foo.min.inline-map" {
  let __exports: any;
  export = __exports;
}

declare module "source-map-explorer/testdata/foo.min" {
  let __exports: any;
  export = __exports;
}

declare module "source-map-explorer/vendor/webtreemap" {
  let __exports: any;
  export = __exports;
}

// Filename aliases
declare module "source-map-explorer/index" {
  let __exports: import("source-map-explorer");
  export = __exports;
}

declare module "source-map-explorer/index.js" {
  let __exports: import("source-map-explorer");
  export = __exports;
}

declare module "source-map-explorer/test.js" {
  let __exports: import("source-map-explorer/test");
  export = __exports;
}

declare module "source-map-explorer/testdata/foo.min.inline-map.js" {
  let __exports: import("source-map-explorer/testdata/foo.min.inline-map");
  export = __exports;
}

declare module "source-map-explorer/testdata/foo.min.js" {
  let __exports: import("source-map-explorer/testdata/foo.min");
  export = __exports;
}

declare module "source-map-explorer/vendor/webtreemap.js" {
  let __exports: import("source-map-explorer/vendor/webtreemap");
  export = __exports;
}
